name: Second Workflow
on:
  workflow_call:
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Check if First Workflow succeeded.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "The upstream CI workflow passed."