name: Orchestrate Pipeline

on:
  push:
    branches:
      - main
jobs:
  call-workflow1:
    uses: ./.github/workflows/workflow_1_pytest.yml

  call-workflow2:
    needs: call-workflow1
    uses: ./.github/workflows/workflow_2_test.yml