name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"] # Matches the 'name:' of the first workflow
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Check if First Workflow succeeded.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "The upstream CI workflow passed."