name: Orchestrate

on:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: ./.github/workflows/workflow_1_pytest.yml
    with:
      environment: 'marktest'

  call-workflow:
    uses: ./.github/workflows/workflow_2_test.yml
    environment: 'marktest'