name: Orchestrate

on:
  push:
    branches:
      - main
jobs:
  run-first:
    uses: ./.github/workflows/workflow_1_pytest.yml

  run-seconds:
    needs: run-first
    uses: ./.github/workflows/workflow_2_test.yml